In [135]:
import pandas as pd
import matplotlib. pyplot as plt
import time

In [4]:
import numpy as np
from IPython.display import clear_output
def read_all_documents(path, N):
    corpus = []
    for f in range(1,N+1):
        file_path = f'{path}/{f}'
        with open(file_path,'r') as file:
            corpus.append(file.read().split())
    return corpus

path = 'pp4data/20newsgroups'
D = 200
corpus = read_all_documents(path, D)

total=0
for i in corpus:
    total+=len(i)
print(total)
N_iters = 500
K = 20
N_words = total
alpha = 5/K
beta = 0.01
v=set()
vocab=[]
for i in corpus:
    v.update(set(i))
for i in (v):
    vocab.append(i)
V = len(vocab)
vocab

8013


['oil',
 'interesting',
 'opinion',
 'black',
 'fluid',
 'mind',
 'shifter',
 'use',
 'vax',
 'auto',
 'nasa',
 'stop',
 'high',
 'program',
 'buying',
 'rear',
 'camaro',
 'extra',
 'shifting',
 'people',
 'net',
 'post',
 'year',
 'range',
 'transmission',
 'launch',
 'mars',
 'interior',
 'love',
 'costs',
 'works',
 'bad',
 'two',
 'systems',
 'spencer',
 'expect',
 'head',
 'pressure',
 'geode',
 'gov',
 'degree',
 'space',
 'bit',
 'alaska',
 'engr',
 'collision',
 'infiniti',
 'zoo',
 'eliot',
 'solar',
 'public',
 'taurus',
 'sci',
 'europe',
 'dealer',
 'wanted',
 'torque',
 'tranny',
 'week',
 'caltech',
 'driver',
 'performance',
 'whether',
 'nothing',
 'months',
 'detectors',
 'info',
 'curious',
 'remember',
 'human',
 'nissan',
 'left',
 'interested',
 'pat',
 'washington',
 'cloud',
 'needed',
 'data',
 'plan',
 'getting',
 'engine',
 'small',
 'local',
 'orbit',
 'stick',
 'case',
 'station',
 'volume',
 'won',
 'news',
 'capability',
 'cmu',
 'resources',
 'uci',
 'le

In [5]:
import random
pi_n = np.random.permutation(total)

w_n=[]
for i in corpus:
    for j in i:
        w_n.append(vocab.index(j))
w_n = np.array(w_n)
        
d_n=[]
for i in range(len(corpus)):
    for j in range(len(corpus[i])):
        d_n.append(i)
d_n = np.array(d_n)

z_n=[]
for i in range(total):
    z_n.append(random.randint(0,K-1))
z_n = np.array(z_n)
    
C_d = np.zeros((D, K))
C_t = np.zeros((K,V))
#print(w_n)
for d in range(C_d.shape[0]):
    for t in range(C_d.shape[1]):
        C_d[d,t] = np.sum(z_n[np.where(d_n==d)[0]]==t)

for t in range(C_t.shape[0]):
    for w in range(C_t.shape[1]):
        C_t[t,w] = np.sum(w_n[np.where(z_n==t)[0]]==w)

size3 = 1*K
#P = np.array([0]*size3).reshape(1, K)
P = np.zeros(K)

#P.shape
#sum(P)

for i in range(N_iters):
    for n in range (N_words):
        word = w_n[pi_n[n]]
        topic = z_n[pi_n[n]]
        #print(topic)
        doc = d_n[pi_n[n]]
        #print(doc)
        C_d[doc][topic] = C_d[doc][topic] - 1
        #print(C_d[doc][topic])
        C_t[topic][word] = C_t[topic][word] - 1
        for k in range(K):
            term1 = ((C_t[k,word] + beta)/(V*beta + np.sum(C_t[k,:])))
            term2 = ((C_d[doc,k] + alpha)/(K*alpha + np.sum(C_d[doc,:])))
            P[k] = term1*term2
        pnorm = sum(P)
        pnorm = pnorm if pnorm>0 else 1
        P = [pp/pnorm for pp in P]
        topic = np.random.choice(np.arange(K), p=P)
        z_n[pi_n[n]] = topic
        C_d[doc][topic] = C_d[doc][topic] + 1
        C_t[topic][word] = C_t[topic][word] + 1

In [6]:
print(z_n)
print(C_d)
print(C_t)
print(vocab)

[13  0 15 ...  0  0  0]
[[ 2.  0.  0. ...  0.  0.  1.]
 [ 2. 59.  0. ...  8.  0.  0.]
 [ 0.  0.  0. ...  0.  1.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  2.]
 [ 0.  0.  0. ...  0.  0.  1.]
 [ 6.  0. 23. ...  0.  2.  3.]]
[[ 0.  0.  0. ...  0.  0.  0.]
 [41.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  9. ...  0.  0.  0.]]
['oil', 'interesting', 'opinion', 'black', 'fluid', 'mind', 'shifter', 'use', 'vax', 'auto', 'nasa', 'stop', 'high', 'program', 'buying', 'rear', 'camaro', 'extra', 'shifting', 'people', 'net', 'post', 'year', 'range', 'transmission', 'launch', 'mars', 'interior', 'love', 'costs', 'works', 'bad', 'two', 'systems', 'spencer', 'expect', 'head', 'pressure', 'geode', 'gov', 'degree', 'space', 'bit', 'alaska', 'engr', 'collision', 'infiniti', 'zoo', 'eliot', 'solar', 'public', 'taurus', 'sci', 'europe', 'dealer', 'wanted', 'torque', 'tranny', 'week', 'caltech', 'driver', 'performance', 'whe

In [7]:
C_t.shape

(20, 405)

In [14]:
newc_t=[]
for i in C_t:
    temp=[]
    for j in i:
        temp.append(j)
    newc_t.append(temp)
newc_t=np.array(newc_t)
newc_t

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [41.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  9., ...,  0.,  0.,  0.]])

In [28]:
csv_file=[]
for j in range(K):
    newarr=sorted(range(len(newc_t[j])), key=lambda i: newc_t[j][i])[-5:]
    temp=[]
    for i in newarr:
        temp.append(vocab[i])
    csv_file.append(temp)
csv_file
import csv


[['people', 'apr', 'article', 'writes', 'edu'],
 ['bmw', 'come', 'service', 'change', 'oil'],
 ['cloud', 'ray', 'oort', 'geico', 'insurance'],
 ['extra', 'interested', 'work', 'speed', 'used'],
 ['probe', 'sho', 'driving', 'ford', 'car'],
 ['small', 'toyota', 'price', 'car', 'engine'],
 ['point', 'large', 'high', 'such', 'even'],
 ['rights', 'light', 'satellite', 'things', 'sky'],
 ['redesign', 'shuttle', 'option', 'launch', 'station'],
 ['planets', 'eliot', 'washington', 'life', 'earth'],
 ['time', 'long', 'moon', 'bill', 'space'],
 ['matter', 'nothing', 'email', 'diesels', 'read'],
 ['net', 'pat', 'shuttle', 'mission', 'hst'],
 ['cars', 'internet', 'article', 'writes', 'edu'],
 ['writes', 'spencer', 'toronto', 'edu', 'henry'],
 ['great', 'howell', 'ford', 'engines', 'george'],
 ['incoming', 'ics', 'uci', 'gif', 'edu'],
 ['drive', 'don', 'shifter', 'car', 'clutch'],
 ['system', 'space', 'gov', 'science', 'nasa'],
 ['make', 'two', 'don', 'find', 'want']]

In [30]:
import csv

# open the file in the write mode
f = open('csv_file', 'w')

# create the csv writer
writer = csv.writer(f)

# write a row to the csv file
writer.writerows(csv_file)

# close the file
f.close()
import pandas as pd
df=pd.read_csv("csv_file",header=None)
df

0           1           2        3          4
0     people         apr     article   writes        edu
1        bmw        come     service   change        oil
2      cloud         ray        oort    geico  insurance
3      extra  interested        work    speed       used
4      probe         sho     driving     ford        car
5      small      toyota       price      car     engine
6      point       large        high     such       even
7     rights       light   satellite   things        sky
8   redesign     shuttle      option   launch    station
9    planets       eliot  washington     life      earth
10      time        long        moon     bill      space
11    matter     nothing       email  diesels       read
12       net         pat     shuttle  mission        hst
13      cars    internet     article   writes        edu
14    writes     spencer     toronto      edu      henry
15     great      howell        ford  engines     george
16  incoming         ics         uci      gif        edu
17     drive         don     shifter      car     clutch
18    system       space         gov  science       nasa
19      make         two         don     find       want

array([[ 2.,  0.,  0., ...,  0.,  0.,  1.],
       [ 2., 59.,  0., ...,  8.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  2.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 6.,  0., 23., ...,  0.,  2.,  3.]])

In [52]:
C_t.shape

(20, 405)

In [68]:
P=[]
for i in range(200):
    temp=[]
    for k in range(K):
        doc=i
        temp.append((C_d[doc,k] + alpha)/(K*alpha + np.sum(C_d[doc,:])))
    P.append(temp)
P=np.array(P)
P

array([[0.1875    , 0.02083333, 0.02083333, ..., 0.02083333, 0.02083333,
        0.10416667],
       [0.02045455, 0.53863636, 0.00227273, ..., 0.075     , 0.00227273,
        0.00227273],
       [0.01086957, 0.01086957, 0.01086957, ..., 0.01086957, 0.05434783,
        0.01086957],
       ...,
       [0.01666667, 0.01666667, 0.01666667, ..., 0.01666667, 0.01666667,
        0.15      ],
       [0.00438596, 0.00438596, 0.00438596, ..., 0.00438596, 0.00438596,
        0.02192982],
       [0.11574074, 0.00462963, 0.43055556, ..., 0.00462963, 0.04166667,
        0.06018519]])

In [81]:
P.shape

(200, 20)

In [80]:
freq=[]
for i in range(len(vocab)):
    freq.append(0)
for i in corpus:
    for j in range(len(vocab)):
        freq[j]=freq[j]+i.count(vocab[j])

405

In [99]:
freq = np.array(freq)

In [100]:
freq.shape

(405,)

In [102]:
partition_values = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]

In [133]:
def newton(newX,Y, data):
    N = newX.shape[0]
    d = newX.shape[1]
    train_size = int((2/3) * len(data))
    xtrain = newX[:train_size]
    ytrain = Y[:train_size]
    xtest = newX[train_size:]
    ytest = Y[train_size:]
   # W_old = np.ones(xtrain.shape[1])
    W_old = np.zeros(xtrain.shape[1])
    alpha = 0.1
    iteration = 0
    weight_vector = {}
    errors = {}
    time_diff = []
    initial_time = time.time()
    while True:
        a = np.dot(xtrain, W_old)
        y = 1/(1 + np.exp(-a))
        #print(y.shape)
        R = np.diag(y*(1-y))
        #print(R.shape,R)
        term_1 = alpha*np.identity(d) + np.dot(np.dot(xtrain.T,R),xtrain)
        term_2 = np.dot(xtrain.T, (y-ytrain)) + alpha*W_old
        W_new = W_old - np.dot(np.linalg.inv(term_1),term_2)
        iteration+=1
        #W_old = W_new
        ts = time.time()
        weight_vector[ts] = W_new 
        
        if ((np.linalg.norm(W_new-W_old)**2)/(np.linalg.norm(W_old)**2)<0.001) or iteration>100:
            break
        else:
            W_old = W_new
    for ts in weight_vector:
                
                
        # SN calculation
        a = np.dot(xtrain, weight_vector[ts])
        y = 1/(1 + np.exp(-a))
        summation = np.zeros((d,d))
        for i in range(y.size):
            summation+= (y[i]*(1-y[i]))*np.dot(xtrain[i,:], xtrain[i,:])
            
        SN = alpha*np.identity(d) + summation
        #predictions

        pred = np.zeros(xtest.shape[0])
        for i in range(pred.size):
            phi = xtest[i,:]
            mu = np.dot(weight_vector[ts].T, phi)
            sigma_sq = np.dot(np.dot(phi.T, SN), phi)
            a = 1/np.sqrt(1 + (np.pi*sigma_sq/8))
            pred[i] = 1/(1 + np.exp(-(a*mu)))
                     
        prediction = np.where(pred>=0.5,1,0)
        error = np.sum(np.logical_xor(ytest, prediction))
        test_error = error/ytest.size
        errors[ts-initial_time] = test_error
        time_diff.append(ts-initial_time)   
            
    return errors, weight_vector, time_diff

In [119]:
labels = pd.read_csv(r'pp4data/20newsgroups/index.csv', header=None)

In [120]:
X1 = P
X2 = freq

In [122]:
N = X1.shape[0]
Y = labels.to_numpy().flatten()
newX = np.c_[np.ones(N),X1]

In [123]:
Y.shape

(400,)

In [126]:
train_size = int((2/3) * len(X1))
xtrain = newX[:train_size]
ytrain = Y[:train_size]
xtest = newX[train_size:]
ytest = Y[train_size:]

In [136]:
errors_newton_A1,weight_vector_newton_A1,t1N = newton(newX,Y,X1)
errors_newton_A2,weight_vector_newton_A2,t2N = newton(newX,Y,X1)
errors_newton_A3,weight_vector_newton_A3,t3N = newton(newX,Y,X1)

<ipython-input-133-6badcf2cc0a0>:31: RuntimeWarning: divide by zero encountered in double_scalars
  if ((np.linalg.norm(W_new-W_old)**2)/(np.linalg.norm(W_old)**2)<0.001) or iteration>100:


ValueError: operands could not be broadcast together with shapes (267,) (67,) 

In [117]:
plt.plot(partition_values, [discriminative_result[(str(pv), 'Discriminative')][0] for pv in partition_values], marker = 'o', label = 'Discriminative Algorithm')
plt.xlabel('Partition Values')
plt.ylabel('Test Set Error')
plt.title('learning curves for dataset  A')
plt.legend()
plt.xticks(partition_values)
plt.show()

KeyError: ('0.1', 'Discriminative')