In [1]:
import numpy as np


In [2]:
#Task 1
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=np.array([11,12,13,14,15,16,17,18,19,20])
arr3=np.array([1,3,5,7,9])
print(arr1+arr2)
print(arr2-arr1)
print(arr1*arr2)
print(arr2/arr1)
print("\n")
a="Hello World"
b=10
c=1.0
d=True
print(bool(a))
print(float(b))
print(int(c))
print(str(d))
print("\n")


[12 14 16 18 20 22 24 26 28 30]
[10 10 10 10 10 10 10 10 10 10]
[ 11  24  39  56  75  96 119 144 171 200]
[11.          6.          4.33333333  3.5         3.          2.66666667
  2.42857143  2.25        2.11111111  2.        ]


True
10.0
1
True




In [3]:
#Task 2
arr4=np.array(["a","b","c","d","e","f","g","h","i","j"])
for it in arr4:
    if it=="d":
        print("four")
    elif it=="i":
        print("eight")
    else:
        print(it)
print("\n")


a
b
c
four
e
f
g
h
eight
j




In [4]:
#Task 3
tup=("Hello","I","am","good")
lis=["one","two","three","four","five","six","seven"]
t1=tup[0]
t2=tup[1]
t3=tup[2]
t4=tup[3]
print(lis.pop())
lis.append(t2)
new_lis=lis[4:]
new_lis.sort()
print(new_lis)
d={"numbers":[1,2,3,4,5,6,7,8,9],"letters":["a","b","c","d","e","f"],"words":["Hello","World"],"Sentences":["Hi how are you","I am fine"],"dates":("1/2/23","1/3/23"),"times":["1:11","2:22","3:33"],"months":["Jan","Feb","Mar"]}
print(d)
print("\n")

seven
['I', 'five', 'six']
{'numbers': [1, 2, 3, 4, 5, 6, 7, 8, 9], 'letters': ['a', 'b', 'c', 'd', 'e', 'f'], 'words': ['Hello', 'World'], 'Sentences': ['Hi how are you', 'I am fine'], 'dates': ('1/2/23', '1/3/23'), 'times': ['1:11', '2:22', '3:33'], 'months': ['Jan', 'Feb', 'Mar']}




In [5]:
#Task 4
arr5=[11,12,13,14,15,16]
for i in arr5:
    print(i+1,"-->",i)
print("\n")

12 --> 11
13 --> 12
14 --> 13
15 --> 14
16 --> 15
17 --> 16




In [6]:
#Task 5
arr6=arr5.copy()
arr6[0]=19
print(arr5)
print(arr6)
print("\n")

[11, 12, 13, 14, 15, 16]
[19, 12, 13, 14, 15, 16]




In [7]:
#Task 6
tup1=(1,2,3,4,5)
try:
    tup1[0]=6
except:
    print("Tuples are immutable")
print("\n")


Tuples are immutable


