In [16]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [17]:
## creating a tensor of 4 rows and 3 columns consisting of ones
x = torch.ones(4, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [18]:
## creating a tensor of 4 rows and 3 columns consisting of zeros
x = torch.zeros(4, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [19]:
## We often set a specific value as random seed to increase the reproducibility
torch.manual_seed(3)
## generating a random tensor
x = torch.rand(4, 3)
print(x)

tensor([[0.0043, 0.1056, 0.2858],
        [0.0270, 0.4716, 0.0601],
        [0.7719, 0.7437, 0.5944],
        [0.8879, 0.4510, 0.7995]])


In [20]:
## generating a random tensor from normal distribution
x = torch.randn(4, 3)
print(x)

tensor([[ 0.3375,  1.0111, -1.4352],
        [ 0.9774,  0.5220,  1.2379],
        [-0.8646,  0.2990,  0.4192],
        [-0.0799,  0.9264,  0.8157]])


In [21]:
## create a tensor with certain values
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
## get the third row (the index start with 0)
print(x[2])
## get the element in row 1, and col 2
print(x[0][1]) # essentially (x[0])[1]
print(x[0, 1])
## get the value of one element tensor by using item()
print(x[0][1].item())
## access a range of elements
print(x[0:3, 0:3]) # start index is 0, end index is 3
                   # the range will include the start index
                   # and exclude the end index

tensor([7, 8, 9])
tensor(2)
tensor(2)
2
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [22]:
## create a tensor with certain values
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
## try to slicing commands
print(x[:, 2]) # Every row, only the last column
print(x[0, :]) # Every column in frist row
y = x[:, 1] # take the elements in the second columns and create another tensor
print(y)

tensor([3, 6, 9])
tensor([1, 2, 3])
tensor([2, 5, 8])


In [23]:
## create a tensor with 3 rows and 2 columns
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
## reshaping to 2 rows and 3 columns
y = x.view(2, 3)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [24]:
## create a tensor with 3 rows and 2 columns
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
## use of -1 to reshaping a tensor
y = x.view(6, -1)
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [31]:
# create two tensors
x = torch.ones([3, 2])
y = torch.ones([3, 2])

# adding two tensors
z1_add = x + y #method 1
z2_add = torch.add(x, y) #method 2
print(z1_add)
print(z2_add)

# substracting two tensors
z1_sub = x - y #method 1
z2_sub = torch.sub(x,y) #method 2
print(z1_sub)
print(z2_sub)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [32]:
## create two tensors
x = torch.ones([3, 2])
y = torch.ones([3, 2])

## multiplying two tensors
z1_mul = x * y # method 1
z2_mul = torch.mul(x, y) # method 2

print(z1_mul)
print(z2_mul)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [33]:
## create two tensors
x = torch.ones(3, 2)
y = torch.ones(3, 2)
print(y)
## inplace operation
z = y.add_(x)
print(y)
print(z)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [45]:

## check the number of CUDA supported GPU that connected to the machine
print(torch.cuda.device_count())
## get the name of the GPU Card
print(torch.cuda.get_device_name(0))


1
Tesla T4


In [61]:
import time
## create numpy tensor with size of (10000,10000)
a = np.random.rand(10000,10000)
a_tensor = torch.from_numpy(a).cpu()
start1 = time.time()
a_tensor_matmul = torch.matmul(a_tensor.T,a_tensor)
print("CPU Seconds passed:{}".format(time.time()-start1))

CPU Seconds passed:54.449613094329834


In [62]:
## performing operations on GPU
## transfer data into cuda
a_tensor_gpu = a_tensor.cuda()
start2 = time.time()
a_tensor_gpu_matmul = torch.matmul(a_tensor_gpu.T,a_tensor_gpu)
print("GPU Seconds passed:{}".format(time.time()-start2))

GPU Seconds passed:0.12426137924194336


In [29]:
## create a tensor with requires_grad = True
## this will track all the operations performing on that tensor
x = torch.ones([3, 3], requires_grad = True)
print(x)

## perform a tensor addition and check the result
y = x + 1
print(y)

## perform a tensor multiplication and check the result
z = y * y
print(z)

## adding all the values in z and check the result
t = torch.sum(z)
print(t)

## perform backpropagation (partial derivate of t with respect to x) and check the result
t.backward()
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], grad_fn=<AddBackward0>)
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]], grad_fn=<MulBackward0>)
tensor(36., grad_fn=<SumBackward0>)
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


In [30]:
import torch
## It is recommended that using a class to customize the Dataset
## so that you can create an iterable loader by DataLoader.
from torch.utils.data import Dataset, DataLoader
## using matplotlib to plot your losses
import matplotlib.pyplot as plt

class train_data(Dataset):
   ## your code is here
   ## you need to define __init__, __len__, __getitem__ at least

class test_data(Dataset):
   ## your code is here

## You can implement the delta_rule and batch_delta_rule with
## functions or classes. The following code is just for reference.
def delta_rule(your_model, your_dataloader):
   ## your code is here
   ## plot your figure of loss changes after training
   ## or return the loss array of each iterations/epochs

def batch_delta_rule(your_model, your_dataloader):
   ## your code is here

## In this case you should run delta_rule(model, train_loader) and
## batch_delta_rule(model, train_loader) respectively.
## Applying the above weights updating methods to train
## your model instead of using the training API of pytorch.
## Again, you can complete it in your own way

IndentationError: ignored